### PR TITLE
Update Feature/dropdown add to body PR branch

### PR DESCRIPTION
**Pull request by andyperlitch**
64 of the commits in this PR are just from merging the current master (there was a conflict in the dropdown README because another feature was added).

The last one is what I did: fixed the tests so that they properly clean up the element in the test launcher and prove that "garbage collection" is in fact occurring.

### CODE REVIEW

**Comment by andyperlitch** [comment]
The only issue I could not fix is removing the commit created from me merging master: [9a5bd0e](https://github.com/andyperlitch/bootstrap/commit/9a5bd0eea9d6187d13a65a934e561aca357a6abc). Other than that it should be good to go.

**Comment by rysilva** [comment]
So logistically, I guess if I were to update my branch before merging this then I would have to deal with the same merge conflict, but it makes it harder to see your actual changes.  I suppose I'll just merge this and then the pull request with angular-ui should be more clear.

**Comment by andyperlitch** [comment]
It looks like @wesleycho wants these commits to be squashed into a single commit...

**Comment by rysilva** [comment]
I should be able to do it later.

**Pull request merged**
